# Generated by Django 4.1 on 2022-08-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
