# Generated by Django 4.1 on 2022-08-27 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blogpostimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostimage',
            name='blogpost',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.blogpost'),
        ),
    ]
