# Generated by Django 4.1 on 2022-08-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blogpostimage_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostimage',
            old_name='name',
            new_name='image',
        ),
        migrations.AddField(
            model_name='blogpostimage',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='upload_thumbnails'),
        ),
    ]
